[package]
name = "human-origin"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
# Le framework principal
tauri = { version = "1", features = [ "shell-open"] }

# Pour le lien magique (Deep Link)
tauri-plugin-deep-link = "0.1"

# SÃ©rialisation JSON (obligatoire pour envoyer les structs au frontend)
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Gestion du temps (obligatoire feature "serde" pour passer les dates en JSON)
chrono = { version = "0.4", features = ["serde"] }

# IDs uniques pour les sessions
uuid = { version = "1.4", features = ["v4"] }

# Capture Clavier / Souris (Keylogger Ã©thique)
device_query = "0.2"

# Pour trouver le dossier "Documents" de l'utilisateur
dirs = "5.0"

# ðŸ‘‡ C'EST CE BLOC QUI MANQUAIT ðŸ‘‡
[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
