[package]
name = "human-origin"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
# On a retiré "system-tray" pour éviter l'erreur précédente
tauri = { version = "1", features = ["shell-open", "http-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# C'est ici que ça se joue pour le Cloud :
reqwest = { version = "0.11", features = ["json"] } 
# Note : Pas besoin d'ajouter tokio explicitement ici, Tauri l'embarque.

# Les outils pour la biométrie et la crypto
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.4", features = ["v4", "fast-rng", "macro-diagnostics"] }
device_query = "0.2"
dirs = "5.0"
base64 = "0.21"
rand = "0.8"
argon2 = "0.5"
aes-gcm = "0.10"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
